OneSignal/OneSignal-Flutter-SDK

- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- android/src/main/java/com/onesignal/flutter/OneSignalSerializer.java
* Set correct <String, Object> mapping types.
* Cleaner call.argument(String) calls
* Marked method private that should be
* Fixed bug with buttons on payload not being set
> Cleaned up types and formatting in Java

- example/lib/main.dart
- lib/onesignal.dart
- lib/src/create_notification.dart
- lib/src/defines.dart
- lib/src/notification.dart
- lib/src/permission.dart
- lib/src/subscription.dart
- lib/src/utils.dart
- test/create_notification_test.dart
- test/mock_channel.dart
- test/notification_test.dart
- test/onesignal_test.dart
- test/permission_test.dart
- test/subscription_test.dart
- test/test_data.dart
• Uses Flutter's autoformat tool to clean up source, clean up string variable embedding, reduce the size of a few lines
> Apply Flutter Autoformat

- android/build.gradle
- changed gradle file to reflect new flutter requirement
> updated compileSdkVersion from 27 to 28

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- android/src/main/java/com/onesignal/flutter/OneSignalSerializer.java
- example/lib/main.dart
- ios/Classes/OneSignalPlugin.m
- lib/onesignal.dart
- lib/src/in_app_message.dart
* All public methods for IAM have been added to Flutter SDK
* main.dart file updated to show examples of IAM action handler and also example IAM methods for triggers and pausing IAMs
* Added a OSInAppMessageAction class for receiving an action object when IAM elements are clicked with actions attached to them
* Updated OneSignal SDK dependency in gradle file to 3.11.1
> Flutter SDK updates for IAM and bug fixes

- example/ios/OneSignalNotificationServiceExtension/OneSignalNotificationServiceExtension.entitlements
- example/ios/Podfile
- example/ios/Podfile.lock
- example/ios/Runner.xcodeproj/project.pbxproj
- example/ios/Runner/Info.plist
- example/ios/Runner/Runner.entitlements
- ios/Classes/OneSignalPlugin.m
* Fixed build issue with Xcode 10 and pod file
* Fixed set external id without a value
* Corrected default Xcode values
> Ios pods and set external id fixes

- CHANGELOG.md
* Change log file to link to the github release notes
* This file must be present to prevent points from being removed on pub.dev.
> Added back changelog file

- README.md
- android/build.gradle
- ios/onesignal_flutter.podspec
- pubspec.yaml
* Updated to OneSignal-iOS-SDK 2.10.1
* Updated to OneSignal-Android-SDK 3.11.2
> Release commit 2.0.2

- android/src/main/java/com/onesignal/flutter/FlutterRegistrarResponder.java
- android/src/main/java/com/onesignal/flutter/OneSignalInAppMessagingController.java
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- android/src/main/java/com/onesignal/flutter/OneSignalTagsController.java
- ios/Classes/OneSignalInAppMessagesController.m
- ios/Classes/OneSignalPlugin.m
- ios/Classes/OneSignalTagsController.m
* iOS bridge missing a few result() calls to prevent hanging awaits/then() from a Future
> Updated a few methods hanging on await statements

- android/build.gradle
- ios/onesignal_flutter.podspec
- pubspec.yaml
* pubspec.yaml is now updated to OS Flutter SDK 2.1.0
* /ios/onesignal_flutter.podspec is now on iOS native 2.11.0 and OS Flutter SDK 2.1.0
* /android/build.gradle is now on Android native 3.11.4 and OS Flutter SDK 2.1.0
> Updated versions across all files for release

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/FlutterRegistrarResponder.java
- android/src/main/java/com/onesignal/flutter/OneSignalInAppMessagingController.java
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- android/src/main/java/com/onesignal/flutter/OneSignalTagsController.java
- example/ios/OneSignalNotificationServiceExtension/NotificationService.m
- ios/Classes/OneSignalCategories.m
- ios/Classes/OneSignalInAppMessagesController.h
- ios/Classes/OneSignalInAppMessagesController.m
- ios/Classes/OneSignalPlugin.m
- ios/Classes/OneSignalTagsController.m
- ios/onesignal_flutter.podspec
- lib/onesignal_flutter.dart
- pubspec.yaml
* Created a OneSignalInAppMessagingController for handling IAM method calls for iOS and Android
* Updated example app NotificationService.m to match documentation
> Updated iOS to include IAM changes

- android/build.gradle
- example/lib/main.dart
- ios/Classes/OneSignalPlugin.m
- ios/onesignal_flutter.podspec
- lib/onesignal_flutter.dart
- pubspec.yaml
* Updated build.gradle, pubspec.yaml, and onesignal_flutterpodspec files with version number
* Native iOS will be using 2.12.1
> Updated for release for 2.3.0

- android/build.gradle
- ios/onesignal_flutter.podspec
- pubspec.yaml
* Includes Android native 3.12.4 and iOS native 2.12.3
> Updating sdk to 2.3.2

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- example/lib/main.dart
- ios/Classes/OneSignalPlugin.m
- ios/onesignal_flutter.podspec
- lib/onesignal_flutter.dart
* Android native now updated to 3.13.0
* iOS native now updated to 2.13.1
* Added external user id callback bridge for Dart and Java/Obj-C code
> Added external user id callback and updated native SDK usage versions

- android/build.gradle
- ios/onesignal_flutter.podspec
- pubspec.yaml
* Updates Android SDK from 3.13.1 to 3.13.2
> Release commit for OS Flutter SDK 2.4.1

- android/build.gradle
- ios/onesignal_flutter.podspec
- pubspec.yaml
* Android bumped to `3.14.1`
* iOS bumped to `2.14.2`
> Release commit for `Flutter` `2.5.0`

- pubspec.yaml
* This was causing an issue from publishing to pub.dev
> Removed `-dev` from flutter version range req

- android/src/main/java/com/onesignal/flutter/FlutterRegistrarResponder.java
Proposal to fix the issue #190 using the same native Android SDK implementation. Please, let's discuss the best solution for this issue.
> Proposal to fix the issue #190 

- android/build.gradle
- ios/onesignal_flutter.podspec
- pubspec.yaml
* Updated to Native Android SDK `3.15.0`, `3.15.1`
* Adds Huawei HMS push and location capabilities
* Updated to Native iOS SDK `2.14.3`
> Release commit for Flutter 2.6.0

- android/build.gradle
- ios/onesignal_flutter.podspec
- pubspec.yaml
* Android Native SDK Update `3.15.3`
- [Release Notes 3.15.3](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.15.3)
- [Release Notes 3.15.2](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.15.2)
* iOS Native SDK Update `2.15.2`
- [Release Notes 2.15.2](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/2.15.2)
> Release commit 2.6.1

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- example/ios/Runner.xcodeproj/project.pbxproj
- example/lib/main.dart
- ios/Classes/OneSignalPlugin.m
- ios/onesignal_flutter.podspec
- lib/onesignal_flutter.dart
* Add authentication support for external Id
* Update callbacks support
> Add support for external id auth hash token

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalOutcomeEventsController.java
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- android/src/main/java/com/onesignal/flutter/OneSignalSerializer.java
- example/ios/Podfile
- example/ios/Runner.xcodeproj/project.pbxproj
- example/lib/main.dart
- ios/Classes/OneSignalPlugin.m
- ios/onesignal_flutter.podspec
- lib/onesignal_flutter.dart
* Add external id auth support
* Update Native version to last stable
Review commit by commit
> Merge Master into major release/ Update to last major release version

- android/build.gradle
- example/ios/Podfile
- ios/onesignal_flutter.podspec
* Update to 3.2.0 Release iOS Version
* Update to 4.1.0 Release Android Version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/346)
> Update SDK Android and iOS Version

- android/build.gradle
- example/ios/Podfile
- example/pubspec.yaml
- ios/onesignal_flutter.podspec
- pubspec.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/380)
> Release commit beta cut 2

- android/src/main/java/com/onesignal/flutter/OneSignalSerializer.java
- lib/src/notification.dart
* Fix OSNotification creation with additional data under Android
* Fix OSNotification creation with background image titleTextColor not being initialize correctly
* Fix OSNotification jsonRepresentation method
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/384)
> Fix notification parsing 

- lib/src/create_notification.dart
- lib/src/notification.dart
* Replace [] initialization deprecated to List<MyClass>.empty(growable: true);
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/385)
> Update List usage

- android/build.gradle
- example/ios/Podfile
- example/pubspec.yaml
- ios/onesignal_flutter.podspec
- pubspec.yaml
* Fix notification parsing  https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/384
* Improve Flutter static analysis https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/385
* Upgrade from Android version 4.3.0 to 4.3.3
* Upgrade from iOS version 3.4.0 to 3.4.3
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/386)
> Release commit beta cut 3

- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- android/src/main/java/com/onesignal/flutter/OneSignalSerializer.java
- example/lib/main.dart
- ios/Classes/OneSignalPlugin.m
- lib/onesignal_flutter.dart
- lib/src/permission.dart
- lib/src/subscription.dart
Add SMS integration 
* Add setSMSNumber and logoutSMSNumber methods
* Add example app SMS Number input and buttons
* Add setSMSSubscriptionObserver method
* Add example app setSMSSubscriptionObserver logger
Note: 
Tests seem to be failing on Travis; Locally, tests are running correctly. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/397)
> Add SMS integration 

- android/build.gradle
- ios/onesignal_flutter.podspec
- pubspec.yaml
* Updated to native [OneSignal-Android-SDK 3.16.0](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.16.0)
- Fixes Compatibility with FCM (Firebase Messaging) 22.0.0.
- Fixes `Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;` error.
* Updated to native [OneSignal-iOS-SDK 2.16.5](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/2.16.5)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/404)
> Release 2.6.4

- android/build.gradle
- example/pubspec.yaml
- ios/onesignal_flutter.podspec
- pubspec.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/406)
> Release commit version 3.0.0

- android/src/main/java/com/onesignal/flutter/OneSignalSerializer.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/446)
> Return SMS user id instead of number

- android/build.gradle
- ios/onesignal_flutter.podspec
- lib/src/defines.dart
- pubspec.yaml
Re-expose notificationPermissionStatus #450 
Feature app defined setLanguage #452
Remove path from pubspec.yaml, it isn't valid #456
Example Switch to iOS pod version range #457
Return SMS user id instead of number #446
Handle handlers more than one response #445
Clean handler before set #443
Update Android version up to 4.4.2
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/458)
> Release commit 3.2.0

- android/build.gradle
- ios/onesignal_flutter.podspec
- lib/src/defines.dart
- pubspec.yaml
- Update iOS to 3.6.2
- Fix OSDeviceState has wrong keys for pushDisabled and subscribed #468
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/471)
> Release 3.2.2

- android/build.gradle
- ios/onesignal_flutter.podspec
- lib/src/defines.dart
- pubspec.yaml
Flutter release to fix iOS binary issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/473)
> release 3.2.3

- android/build.gradle
- lib/src/defines.dart
- pubspec.yaml
* update Android to  [4.6.2](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.6.2)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/503)
> Release 3.2.5

- android/build.gradle
- ios/onesignal_flutter.podspec
- lib/src/defines.dart
- pubspec.yaml
- update Android to [4.6.3](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.6.3)
- update iOS to [3.9.0](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.9.0)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/508)
> Release 3.2.6

- android/build.gradle
- ios/onesignal_flutter.podspec
- lib/src/defines.dart
- pubspec.yaml
* Bump to lastest OneSignal-iOS-SDK 3.10.0
* Bump to lastest OneSignal-Android-SDK 4.6.6
* #518
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/533)
> 3.2.8 Release

- android/build.gradle
- ios/onesignal_flutter.podspec
- lib/src/defines.dart
- pubspec.yaml
- #542
- #523
- #531
- #534
Update `OneSignal-Android-SDK` from `4.6.6` to `4.7.0`
Update `OneSignal-iOS-SDK` from `3.10.0` to `3.10.1`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/543)
> Release 3.3.0

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
adding template according to this guide https://github.com/OneSignal/sdk-repo-guidance/blob/main/docs/whate-are-pr-templates.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/545)
> Adding a pr template

- android/build.gradle
- ios/onesignal_flutter.podspec
- lib/src/defines.dart
- pubspec.yaml
iOS is using 3.11.1 and Android is using 4.7.3
> Release 3.3.1

- android/build.gradle
- ios/onesignal_flutter.podspec
- lib/src/defines.dart
- pubspec.yaml
Native iOS bump to [3.11.2](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.11.2)
SetLanguage callbacks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/570)
> Release 3.3.2

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- example/android/app/build.gradle
- example/android/app/src/main/AndroidManifest.xml
- lib/onesignal_flutter.dart
This PR implements push prompting in Android for Android 13 devices.
There is no public API change for this, instead the existing push prompting API will now work on Android for Android devices 13+. In order to not immediately be prompted in Android 13 apps will need to set their Android target SDK version to 33+.
New Android 13 feature
Push prompting
I tested on both iOS and Android devices for both accepting and denying permissions.
- WIP (Work In Progress) is ok, but explain what is still in progress and what you would like …
> Android 13 push prompting

- pubspec.yaml
This version includes the Android 13 push prompt feature
The iOS and Android native versions are already up to date
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/580)
> Release 3.4.0

- android/build.gradle
- ios/onesignal_flutter.podspec
- pubspec.yaml
- update Android SDK to 4.8.2 which includes this fix
- https://github.com/OneSignal/OneSignal-Android-SDK/pull/1621
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/586)
> 3.4.1 Release

- .github/workflows/ci.yml
Adds a GitHub Action to perform static analysis, ensure correct code formatting, and run unit tests.
This work is intended to ensure quality is maintained across continued development. 
This action will run on **all** PRs. While I generally don't agree with this strategy, it's the strategy @emawby says we should use now. 
I made this action dispatchable, so you can run it from the actions menu after selecting the base branch of this PR; however, this PR has to be merged before you can dispatch the action.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/594)
> Add CI Action

- android/build.gradle
- ios/onesignal_flutter.podspec
- pubspec.yaml
- Update to [OneSignal-iOS-SDK 3.11.4](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.11.4)
**Full Changelog**: https://github.com/OneSignal/OneSignal-Flutter-SDK/compare/3.4.1...3.4.2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/606)
> Release 3.4.2

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Adding the release drafter action for consistent release note formatting.
This is the same release template as native SDKs with an added Dependency section where we can mention iOS and Android native SDK updates
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/632)
> Adding the release drafter action 

- android/src/main/java/com/onesignal/flutter/OneSignalLocation.java
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- example/lib/main.dart
Adding the Android implementation for the Location namespace methods whether location is shared or not.
`OneSignal.Location.requestPermission();`
`const shared = OneSignal.Location.isShared()`
`OneSignal.Location.setShared(true);`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/652)
> [User Model] Location method implementation + Android

- android/src/main/java/com/onesignal/flutter/FlutterRegistrarResponder.java
- android/src/main/java/com/onesignal/flutter/OneSignalInAppMessages.java
- android/src/main/java/com/onesignal/flutter/OneSignalNotifications.java
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- android/src/main/java/com/onesignal/flutter/OneSignalPushSubscription.java
- android/src/main/java/com/onesignal/flutter/OneSignalSerializer.java
- android/src/main/java/com/onesignal/flutter/OneSignalUser.java
- example/lib/main.dart
- lib/src/notification.dart
- lib/src/user.dart
Cleaning up notifications handlers and types on android
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/660)
> [User Model] Testing cleanup and fixes

- android/build.gradle
- ios/onesignal_flutter.podspec
- pubspec.yaml
Flutter User Model Release 5.0.0 Beta 1
[Migration Guide](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/user_model/main/MIGRATION_GUIDE.md)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/666)
> [User Model] Release 5.0.0 Beta 1

- MIGRATION_GUIDE.md
- android/build.gradle
- example/android/app/build.gradle
- example/ios/Flutter/Flutter.podspec
- example/ios/Podfile
- example/ios/Podfile.lock
- example/ios/Runner.xcodeproj/project.pbxproj
- example/lib/main.dart
- ios/Classes/OneSignalPlugin.m
- ios/onesignal_flutter.podspec
- lib/onesignal_flutter.dart
Remove setLaunchURLsInApp and prepare for GA release
- remove setLaunchURLsInApp code
- Bump native versions to the GA releases
- Bump minSDKVersion on Android to 19 in the example app
- Update the example app podfile
Tested on iOS and Android emulators
- - - …
> [User model] remove set launch urls and update to native user model GAs

- MIGRATION_GUIDE.md
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- pubspec.yaml
⚠️ This is a major release which contains breaking API changes.
In this major version release for the OneSignal Flutter SDK, we are making a significant shift from a device-centered model to a user-centered model. A user-centered model allows for more powerful omni-channel integrations within the OneSignal platform.
For information please see the [migration guide](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/user_model/main/MIGRATION_GUIDE.md).
- `setLaunchURLsInApp` has been removed
**Note that Identity Verification has not yet been enabled in this version and will be released in a later version**
Full Changelog since beta 2: https://github.com/OneSignal/OneSignal-Flutter-SDK/compare/5.0.0-beta2...5.0.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
> Flutter release 5.0.0

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- ios/Classes/OneSignalPlugin.m
- ios/onesignal_flutter.podspec
- pubspec.yaml
🐛 Bug Fixes
- Fix `permission` not updating during a session #735 
- Fix crash when using non-string tag values #733 
**Android Native SDK Changes**
- Fix proguard rules to allow minify to be enabled https://github.com/OneSignal/OneSignal-Android-SDK/pull/1828
Full Changelog: https://github.com/OneSignal/OneSignal-Flutter-SDK/compare/5.0.0...5.0.1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/737)
> Release 5.0.1

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- example/ios/Podfile
- ios/Classes/OneSignalPlugin.m
- ios/onesignal_flutter.podspec
- pubspec.yaml
**🐛 Bug Fixes**
* https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/743
* https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/752
* https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/753
**🔧 Maintenance**
* https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/744
* Updated included Android SDK to [5.0.2](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.0.2)
* Updated included iOS SDK to [5.0.2](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.0.2)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/754)
> Release 5.0.2

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- ios/Classes/OneSignalPlugin.m
- ios/onesignal_flutter.podspec
- pubspec.yaml
* Updated included Android SDK to [5.0.3](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.0.3)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/760)
> Release 5.0.3

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- ios/Classes/OneSignalPlugin.m
- ios/onesignal_flutter.podspec
- pubspec.yaml
- Fix clearTriggers on Android in https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/771
- Update Android SDK to [5.0.4](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.0.4)
- Update iOS SDK to [5.0.4](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.0.4)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/787)
> Release 5.0.4

- MIGRATION_GUIDE.md
- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalUser.java
- example/lib/main.dart
- ios/Classes/OSFlutterUser.m
- ios/onesignal_flutter.podspec
- lib/src/user.dart
Add public api method, getTags, that returns the dictionary of local tags on the current user.
Add requested getTags method
Tested getTags on an user with tags and with no tags, app build with a fresh install of the OneSignal example app on on a emulated Pixel 4 with Android 12 and physical iPhone 12 with iOS 15.5.
- - - …
> [Feature] Get tags

- .github/workflows/set_response_time.yml
Fix set response time action failing
Fix issue with node version in action > 6.0.6
https://github.com/octokit/action.js/issues/565
Fix workflow run
Same issue as on Android https://github.com/OneSignal/OneSignal-Android-SDK/pull/1941
set response time workflow
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/808)
> [Dev] Update set_response_time.yml 

- android/build.gradle
- ios/onesignal_flutter.podspec
- pubspec.yaml
**🔧 Maintenance**
- Added the `namespace` property in `build.gradle` to support AGP 8 https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/765
**Native iOS SDK Update**
Bump native iOS SDK version from `3.12.4` to `3.12.7`: See release [notes](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.12.7)
**Native Android SDK Update**
Bump native Android SDK version from `4.8.5` to `4.8.7`: See release [notes](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.8.7)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/832)
> Release 3.5.2

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- ios/Classes/OneSignalPlugin.m
- ios/onesignal_flutter.podspec
- pubspec.yaml
- Update Android SDK from `5.1.2` to `5.1.6`: [5.1.6 Release Notes](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.6)
- Which include an improvement to banner-style IAMS: [link](https://github.com/OneSignal/OneSignal-Android-SDK/pull/1999), a dependency update for `firebase-messaging` and `play-services-basement`
- Also includes fix for null pointer exceptions from calling `getAppContext` when the SDK is initializing: [link](https://github.com/OneSignal/OneSignal-Android-SDK/pull/2012)
- For full changes, see the native release notes: [link](https://github.com/OneSignal/OneSignal-Android-SDK/releases)
- Update iOS SDK from `5.1.0` to `5.1.1`: [5.1.1 Release Notes](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.1.1)
- Includes fix to improve Swift …
> Release 5.1.1

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- ios/Classes/OneSignalPlugin.m
- ios/onesignal_flutter.podspec
- pubspec.yaml
- Update Android SDK from `5.1.2` to `5.1.6`
- Which include an improvement to banner-style IAMS: [link](https://github.com/OneSignal/OneSignal-Android-SDK/pull/1999), a dependency update for `firebase-messaging` and `play-services-basement`
- Also includes fix for null pointer exceptions from calling `getAppContext` when the SDK is initializing: [link](https://github.com/OneSignal/OneSignal-Android-SDK/pull/2012)
- For full changes, see the native release notes: [link](https://github.com/OneSignal/OneSignal-Android-SDK/releases)
- Update iOS SDK from `5.1.0` to `5.1.3`: [5.1.3 Release Notes](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.1.3)
- Includes fix to improve Swift concurrency safety to address crash reports in production: …
> Release 5.1.2

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- ios/Classes/OneSignalPlugin.m
- ios/onesignal_flutter.podspec
- pubspec.yaml
🐛 Bug Fixes
- Fix Live Activities methods were not working due to bridge error (#860)
🎉 New Methods
- Add getter for onesignalId and externalId and a UserState Observer to be notified of changes (#856)
- See the [User Namespace API Reference](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/main/MIGRATION_GUIDE.md#user-namespace) in the Migration Guide for usage
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/862)
> Release 5.1.3

- android/build.gradle
- ios/onesignal_flutter.podspec
- pubspec.yaml
- Updated included Android SDK from 4.8.7 to [4.8.8](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.8.8)
- For full changes, [see the native release notes](https://github.com/OneSignal/OneSignal-Android-SDK/releases)
- Updated included iOS SDK from 3.12.7 to [3.12.9](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.12.9)
- Added privacy manifests
- For full changes, [see the native release notes](https://github.com/OneSignal/OneSignal-iOS-SDK/releases)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/866)
> Release 3.5.3

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- ios/Classes/OneSignalPlugin.m
- ios/onesignal_flutter.podspec
- pubspec.yaml
**Update Android SDK from `5.1.8` to `5.1.9`**
- [5.1.9 release notes](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.9)
- Added Network call optimizations
- Fix for WorkManager not initialized crash
- Added `AndroidManifest` options to override In-App Messages **gray overlay** and **dropshadow** 
```
<meta-data android:name="com.onesignal.inAppMessageHideGrayOverlay" android:value="true"/>
<meta-data android:name="com.onesignal.inAppMessageHideDropShadow" android:value="true"/>
```
**Update iOS SDK from `5.1.4` to `5.1.5`**
- [5.1.5 Release Notes](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.1.5)
- ✨ In-App Message Enhancements:
- The **status bar** will be hidden on full-bleed In-App Messages
- Add back the **dropshadow** on In-App Messages and …
> Release 5.1.5

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- ios/Classes/OneSignalPlugin.m
- ios/onesignal_flutter.podspec
- pubspec.yaml
**Update Android SDK from `5.1.9` to `5.1.10`**
- [5.1.10 release notes](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.10)
- 🛠️ Added additional Network call optimizations
- 🐛 Handle incorrect 404 responses; add a delay after creates and retries on 404 of new ids [#2095](https://github.com/OneSignal/OneSignal-Android-SDK/pull/2059)
**Update iOS SDK from `5.1.5` to `5.1.6`**
- [5.1.6 Release Notes](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.1.6)
- 🐛 Bug Fixes
- Fix crashes when encoding user models [#1412]([OneSignal/OneSignal-iOS-SDK#1412](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1412))
- Some pending properties can be sent to new user, when users change quickly after the last updates are made …
> Release 5.1.6

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- ios/Classes/OneSignalPlugin.m
- ios/onesignal_flutter.podspec
- pubspec.yaml
- chore: add warning for identity verification in https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/901
- [release notes](https://github.com/OneSignal/OneSignal-Android-SDK/releases)
- Fix "could not be instantiated" exception when; some modules are omitted AND android.enableR8.fullMode is enabled. https://github.com/OneSignal/OneSignal-Android-SDK/pull/2136
- [release notes](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.2.2)
- Prevent In-App Message request crashes by making null values safe https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1457
- Add Dispatch Queues to all executors to prevent concurrency crashes https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1454
- Fix clearing notifications incorrectly such as when pulling down the notification center …
> Release 5.2.2

- MIGRATION_GUIDE.md
Removed duplicate "longer" MIGRATION_GUIDE.md
**REQUIRED -** This ensures better readability for the one signal flutter docs.
**RECOMMEND - OPTIONAL -** Migration guide docs.
- [] I have included test coverage for these changes, or explained why they are not needed
- - - …
> Removed duplicate "longer" MIGRATION_GUIDE.md

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- ios/Classes/OneSignalPlugin.m
- ios/onesignal_flutter.podspec
- pubspec.yaml
- Removed duplicate "longer" MIGRATION_GUIDE.md (#914)
- Set wrapper sdk type before calling initialize (#932)
🐛 Bug Fixes
* IAM with dynamic trigger showing forever (https://github.com/OneSignal/OneSignal-Android-SDK/pull/2137)
* Allow preventDefault to be fired up to two times (https://github.com/OneSignal/OneSignal-Android-SDK/pull/2138)
* Recover null onesignal ID crashes for Operations (https://github.com/OneSignal/OneSignal-Android-SDK/pull/2157)
*Prevent retrying IAM display if 410 is received from backend (https://github.com/OneSignal/OneSignal-Android-SDK/pull/2158)
✨ Improvements
- Optimized the initialization process by moving some service initialization to a background thread (https://github.com/OneSignal/OneSignal-Android-SDK/pull/2151)
- Add option to default to HMS over FCM …
> Release 5.2.3

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- ios/Classes/OneSignalPlugin.m
- ios/onesignal_flutter.podspec
- pubspec.yaml
- https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/935
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/941)
> Release 5.2.4

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- ios/Classes/OneSignalPlugin.m
- ios/onesignal_flutter.podspec
- pubspec.yaml
**🐛 Bug Fixes**
- Fix ending an already ended session (https://github.com/OneSignal/OneSignal-Android-SDK/pull/2185)
- Fix Permissions returned by onRequestPermissionResult is empty (https://github.com/OneSignal/OneSignal-Android-SDK/pull/2180)
- Fix Keyboard input in HTML In App Messages (https://github.com/OneSignal/OneSignal-Android-SDK/pull/2187)
**✨ Improvements**
- [Fix] Handle incorrect 404 by delaying making updates to new users or subscriptions (https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1470)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/948)
> Release 5.2.5

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- ios/Classes/OneSignalPlugin.m
- ios/onesignal_flutter.podspec
- pubspec.yaml
--------
🐛 Bug Fixes
- Pausing IAMs dismisses any currently showing IAM [#2191](https://github.com/OneSignal/OneSignal-Android-SDK/pull/2191)
✨ Improvements
- (For our server only) Improve accuracy of targeting users and subscriptions [#2168](https://github.com/OneSignal/OneSignal-Android-SDK/pull/2168)
✨ Improvements
- Pausing IAMs dismisses any currently showing IAM [#1480](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1480)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/960)
> Release 5.2.6

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- ios/Classes/OneSignalPlugin.m
- ios/onesignal_flutter.podspec
- pubspec.yaml
--------
🐛 Bug Fixes
- [Fix] ANR caused by operationRepo.enqueue while loading is in progress [#2233](https://github.com/OneSignal/OneSignal-Android-SDK/pull/2233)
- [Fix] Check subscription Id before executing delete and update subscription operations [#2223](https://github.com/OneSignal/OneSignal-Android-SDK/pull/2223)
🐛 Bug Fixes
- [Fix] Use new OneSignalClientError type for callbacks which fixes crash report of NSInvalidArgumentException [#1528](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1528)
- [Fix] Don't evaluate in app messages when paused which fixes issues with duration-since-last In-App Messages when pausing and unpausing [#1524](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1524)
- - - …
> Release 5.2.9

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- ios/Classes/OneSignalPlugin.m
- ios/onesignal_flutter.podspec
- pubspec.yaml
Channels: Current
- #995
---------
**Update Android SDK from 5.1.29 to 5.1.33 | select fixes listed**
- [Fix] very rare bug where app doesn't opening from notification tap when it cold starts the app, affects Samsung and Redmi (https://github.com/OneSignal/OneSignal-Android-SDK/pull/2289)
- IAM not showing fixes: (https://github.com/OneSignal/OneSignal-Android-SDK/pull/2287) and (https://github.com/OneSignal/OneSignal-Android-SDK/pull/2284)
- Fix: ANR fixes (https://github.com/OneSignal/OneSignal-Android-SDK/pull/2281)
- See [release notes](https://github.com/OneSignal/OneSignal-Android-SDK/releases) for full details.
**Update iOS SDK from 5.2.10 to 5.2.11**
- Synchronize to fix crashes in the user module (https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1554)
- See [release …
> Release 5.3.1

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- ios/Classes/OneSignalPlugin.m
- ios/onesignal_flutter.podspec
- pubspec.yaml
Channels: Current
- [Switch docs for setShared and isShared #995](https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/995)
---------
**Update Android SDK from 5.1.29 to 5.1.33 | select fixes listed**
- [Fix] very rare bug where app doesn't opening from notification tap when it cold starts the app, affects Samsung and Redmi (https://github.com/OneSignal/OneSignal-Android-SDK/pull/2289)
- IAM not showing fixes: (https://github.com/OneSignal/OneSignal-Android-SDK/pull/2287) and (https://github.com/OneSignal/OneSignal-Android-SDK/pull/2284)
- Fix: ANR fixes (https://github.com/OneSignal/OneSignal-Android-SDK/pull/2281)
- See [release notes](https://github.com/OneSignal/OneSignal-Android-SDK/releases) for full details.
- - - …
> Release 5.3.2

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/workflows/project.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/1030)
> Add Project Workflow

- .github/ISSUE_TEMPLATE/ask-question.yml
- .github/ISSUE_TEMPLATE/general-feedback.yml
- .github/workflows/project.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/1032)
> Update project workflow

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
- ios/Classes/OneSignalPlugin.m
- ios/onesignal_flutter.podspec
- pubspec.yaml
Channels: Current
**Update Android SDK from 5.1.33 to 5.1.34**
- https://github.com/OneSignal/OneSignal-Android-SDK/pull/2305
- https://github.com/OneSignal/OneSignal-Android-SDK/pull/2304
- https://github.com/OneSignal/OneSignal-Android-SDK/pull/2296
- See [release notes](https://github.com/OneSignal/OneSignal-Android-SDK/releases) for full details.
**Update iOS SDK from 5.2.10 to 5.2.12**
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1554
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1559
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1568
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1565
- See [release notes](https://github.com/OneSignal/OneSignal-iOS-SDK/releases) for full details.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
> Release 5.3.3

- android/build.gradle
- android/src/main/java/com/onesignal/flutter/OneSignalUser.java
- example/ios/Podfile.lock
- example/lib/main.dart
- ios/Classes/OSFlutterUser.m
- ios/onesignal_flutter.podspec
- lib/src/user.dart
- add custom events for onesignal flutter package
- added `trackEvent` method to the user state class
- exposed `trackEvent` methods for android and ios via `OneSignalUser.java` and `OSFlutterUser.m` respectively 
- updated require android sdk to 5.3.0-alpha-01 and ios to `5.4.0-alpha-01`
- updated flutter example configs to be able to run
- updated flutter example have to new `trackEvent` button action/demo
- This is pr to add custom events support for the flutter sdk.
- We want allow this beta feature to be used in more platforms like flutter, react-native, etc.
Run the example via `flutter run` and clicked the track event button to initiate that action.
- tested with iPhone 16 (iOS 18) emulator
- tested on Android (15) emulator
- If it is hard to explain how any codes changes are …
> feat: add custom events support for flutter
