lib/onesignal.dart
lib/src/notification.dart
lib/src/permission.dart
lib/src/subscription.dart
test/mock_channel.dart
test/permission_test.dart
test/subscription_test.dart

• Discovered that non-string values are not allowed to exist in notifications/tags/etc, so I have changed the SDK to use Map<String, dynamic> instead of allowing dynamic keys.
• Because of how Dart's cast system works, this requires us to explicitly use cast<String, dynamic>()

Switch to Explicit cast()

---

android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java

• The OneSignalPlugin was initializing the native OneSignal SDK with an incorrect context. Switched to using the flutter registrar's activeContext instead.
• This would have caused the SDK to always believe that the app was not currently in focus, meaning the SDK would ignore the current inFocusDisplayType option and always show notifications as normal Android notifications
• Fixes issue #7

Fix Incorrect Context

---

lib/onesignal.dart

• Fixes an issue with the SDK that would print a warning for the private _handleMethod() method.
• It was returning the results of calling private handler references, which themselves returned void. However the function is defined to return Future<Null> not void, so a warning was printed.
• Fixed by returning null at the end. The result of this function is not used and the SDK does not need to wait asynchronously for the handlers to finish executing.
• Fixes #14 
**NOTE** The typical reviewer for these PR's (@jkasten2) is out on vacation for the next week, so to avoid delaying builds, we will merge and release without review.

Fix Type Conversion Warning

---

lib/onesignal.dart
test/onesignal_test.dart

• The init() method is intended to accept iOS Settings as an optional parameter
• However it appears that it would cause an exception if settings were not provided.
• Added regression test case to ensure init() works without iOS Settings
• Fixes #11 
**NOTE** The typical reviewer for these PR's (@jkasten2) is out on vacation for the next week, so to avoid delaying builds, we will merge and release without review.

Fix Initialization Exception

---

android/src/main/java/com/onesignal/flutter/OneSignalSerializer.java

• Fixes a null pointer exception in our JSONObject -> Hash Map helper conversion function
• It turns out that if there is a null value in a JSON object, using an equality check against null (obj == null) will return false
• This is because in Android's JSONObject implementation, null values are actually pointers to JSONObject.NULL and an equality check against Java's null will return false
• Fixed by checking for this case and will skip adding null values to hashmaps (which would throw an exception in Flutter's Java wrapper)

Fix JSON Null Pointer Exception

---

android/build.gradle
android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
example/ios/Podfile
example/lib/main.dart
example/pubspec.yaml
ios/Classes/OneSignalPlugin.m
ios/onesignal.podspec
lib/onesignal.dart
pubspec.yaml
test/mock_channel.dart
test/onesignal_test.dart

• Adds `setExternalUserId(String)` and `removeExternalUserId()` functions to the SDK
• Updates the iOS and Android native SDK's
• Updates the example project to add external user ID buttons for testing purposes

Set External ID

---

android/src/main/java/com/onesignal/flutter/FlutterRegistrarResponder.java
android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
android/src/main/java/com/onesignal/flutter/OneSignalTagsController.java

* Removed use of android.support.annotations which was included for @NonNull
* This was done instead of switches these .java source files to AndroidX as the main native OneSignal SDK hasn't switch over yet.
- Also having a mixture would add more confusion and would require Jetifier to always be enabled

Removed Android Support use in wrapper code

---

android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java

* When a user triggers onDestroy, callbacks no longer have proper context so they must be destroyed
* This saves queues the actions until a new callback is set and then fires them correctly
* This is for notification received, opened, and in app messaging action

Added a callback to connect flutterRegistrar plugin to app onDestroy

---

lib/onesignal_flutter.dart

This function didn't do anything and was throwing an error when used. `fallbackToSettings` should be used instead when prompting
Fixes #129

Removed presentApplicationSettings in favor of fallbackToSettings

---

android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java

* setEmail did not work on Android without emailAuthHash
- Nor did it resolve its Future.
* Removed null checking for both email and emailAuthHash as the native Android setEmail already handles this.
* Fixes #214

Fixed setEmail without emailAuthHash for Android

---

lib/src/create_notification.dart
test/create_notification_test.dart

This change fixes the `delayed_option` property which was uncorrectly specified and it is currently breaking the option to schedule notifications from the client.
fix #267

fix(delayed_option): allow to schedule notifications

---

pubspec.yaml

* pluginClass is deprecated, it can only be defined under platforms
When trying to upload new Flutter version following error was shown:
Package validation found the following error:
* In pubspec.yaml the flutter.plugin.{androidPackage,iosPrefix,pluginClass} keys are deprecated. Instead use the flutter.plugin.platforms key introduced in Flutter 1.10.0
See https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin

Migrate pluginClass to new format

---

pubspec.yaml

Update minimum flutter version to 1.10.0, this version is required to user platform pluginClass. Last pluginClass format was deprecated as pointed out under https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/342
Checking flutter release notes seems to be safe to increase the min flutter SDK version since there are a lot of changes in past releases, we will need to update later on and since there is no more support to old versions, we should keep following https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin instructions
https://flutter.dev/docs/development/tools/sdk/release-notes
Flutter error change
https://github.com/dart-lang/pub/pull/2502/files
--- …

Update flutter min version

---

android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
lib/onesignal_flutter.dart

- Add Android method userProvidedPrivacyConsent support
- Add Android clearOneSignalNotifications method support
- Add Android removeNotification method support
We should add all this method under OneSignal.m iOS public native SDK so we can support them on Flutter and React Native
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/347)

Add missing method support

---

ios/onesignal_flutter.podspec
pubspec.yaml

* Updated to use the latest 2.16.3 version of OneSignal swift api
* Updated the Android package definition to use the correct syntax for package name declaration (was causing a compile error/warning due to using an outdated def)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/349)

Fix FCM compatibility and Android package definition

---

android/src/main/java/com/onesignal/flutter/OneSignalSerializer.java
example/ios/Podfile
example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
example/lib/main.dart
example/pubspec.yaml
lib/onesignal_flutter.dart
lib/src/create_notification.dart
lib/src/in_app_message.dart
lib/src/notification.dart
lib/src/permission.dart
lib/src/subscription.dart
lib/src/utils.dart
pubspec.yaml
test/create_notification_test.dart
test/mock_channel.dart
test/notification_test.dart
test/onesignalflutter_test.dart

* Add Null safety support
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/370)

Migrate to Flutter 2

---

android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
android/src/main/java/com/onesignal/flutter/OneSignalSerializer.java
ios/Classes/OneSignalPlugin.m
lib/src/notification.dart

Fix Android handler 
* Add in-app message handler listener
* Fix grouped notification parsing, not add to JSON if is an empty array
* Fix action id, make it optional
* Add notification open handler listener
Fix iOS Notification open handler
* Add open handler listener
* Add cold start support --> Not working
On iOS notification, the open handler is not being called when the app is swiped away. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/375)

Fix handlers

---

android/src/main/java/com/onesignal/flutter/OneSignalSerializer.java

* Fix parsing issue, rename key from launchURL to launchUrl
Fixes 
https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/392
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/398)

Fix launchUrl Android returning null

---

android/build.gradle
example/ios/Podfile
example/pubspec.yaml
ios/onesignal_flutter.podspec
pubspec.yaml

* Fix launch URL always returning null on Android https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/398
* Upgrade from Android version 4.3.3 to 4.4.0
- See full release notes https://github.com/OneSignal/OneSignal-Android-SDK/releases
* Upgrade from iOS version 3.4.3 to 3.4.4
- See full release notes https://github.com/OneSignal/OneSignal-iOS-SDK/releases
* Update pod file to use XCFramework
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/400)

Release commit beta cut 4

---

android/src/main/java/com/onesignal/flutter/OneSignalSerializer.java
lib/src/notification.dart

See https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/377#issuecomment-868393081.
The problem is that it is not possible to pass the current content `groupedNotifications` through [MethodChannel](https://api.flutter.dev/flutter/services/MethodChannel-class.html). Pull request fixes crash when user clicks on grouped push notifications.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/423)

Fix serialization for grouped notification

---

android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java

* Avoid handlers being set more that once, native side will keep reference too all handlers set
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/443)

Clean handler before set

---

lib/src/defines.dart
lib/src/permission.dart

This was exposed in the past but appears to have been hidden with the 3.x refactor.
I also added OSNotificationPermission.ephemeral to match the underlying platform SDKs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/450)

Re-expose notificationPermissionStatus

---

android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
example/ios/Podfile
ios/Classes/OneSignalPlugin.m
ios/onesignal_flutter.podspec
lib/onesignal_flutter.dart
test/mock_channel.dart
test/onesignalflutter_test.dart

Add feature app-defined language implementation to OneSignal-Flutter-SDK. A user can define their own language setting to be used by OneSignal-SDK
* Add `setLanguage` method to OneSignal Android plugin 
* Add `setLanguage` method to OneSignal iOS plugin
* Update Podfile and onesignal_flutter.podspec files with `OneSignalXCFramework 3.6.0`
* Add `setLanguage` bridge methods to onesignal_flutter.dart
* Test device using button click to call _handleSetLanguage to set it to language different from language defined by the app. OneSignal app dashboard reflects the language set using OneSignal.setLanguage
* Add unit test defining 'fr' using `setLanguage` callback that expects `language` returned to be the same
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

Feature app defined setLanguage

---

example/pubspec.yaml

* Path results in pub not being able to find the onesignal_flutter package.
* Fixes the following error
- pub get failed (66; Because onesignal_example depends on onesignal_flutter from path which doesn't exist (could not find package onesignal_flutter at "^3.1.0"), version solving failed.)
* Tested with Flutter 2.2.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/456)

Remove path from pubspec.yaml, it isn't valid

---

android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java

Add single response handler 
* Some calls might end being called twice from the native side. Even if we already cover this from the native side, add safe
check to avoid more than one call to the same flutter response
Clear handlers commit already approved, review commit "Add single response handler"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/445)

Single response

---

example/ios/Podfile
example/ios/Podfile.lock

Fixes example build for iOS due to picking a mixture of OneSignalXCFramework versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/457)

Example Switch to iOS pod version range

---

lib/src/permission.dart
lib/src/subscription.dart
test.json
test/subscription_test.dart

Renaming Subscription State properties from:
- `subscribed` to `isSubscribed`
- `userSubscriptionSetting` to `isPushDisabled`
- This was not issue on latest 2.x.x Flutter SDK (2.6.4 at time of writing, using Android SDK 3.16.0) which uses the old key names
- This is needed because those are used in the JSON sent from the `DeviceState` after Android SDK 4.x.x
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/463)

Rename properties to `isSubscribed` and `isPushDisabled`

---

ios/onesignal_flutter.podspec
lib/src/notification.dart

iOS 15 notification properties are now available in the iOS native SDK. This PR adds the properties to the Flutter OSNotification object.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/489)

adding relevanceScore and interruptionLevel to Notification.dart

---

.gitignore
android/src/main/java/com/onesignal/flutter/FlutterRegistrarResponder.java
android/src/main/java/com/onesignal/flutter/OneSignalInAppMessagingController.java
android/src/main/java/com/onesignal/flutter/OneSignalOutcomeEventsController.java
android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
android/src/main/java/com/onesignal/flutter/OneSignalTagsController.java
example/.gitignore
example/android/app/src/main/AndroidManifest.xml
example/android/app/src/main/java/com/onesignal/onesignalexample/MainActivity.java
example/android/app/src/main/res/values/styles.xml

As requested here [Issue 480](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/480), it's necessary to update the Android implementation to support the v2 Embedding which it's the default for new Android plugins and it is highly recommended to be update it because future release of Flutter will fail to build with deprecated Android embedding.
I migrated the Android implementation to support embedding v2 while remaining compatible with apps that don’t use the v2 Android embedding.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/486)

Android plugin API updated to support v2 Embedding

---

android/build.gradle
ios/onesignal_flutter.podspec
lib/src/defines.dart
pubspec.yaml

- update iOS to [3.9.1 ](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.9.1) which adds back architectures to OneSignalXCFramework
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/511)

Release 3.2.7

---

test/mock_channel.dart

I noticed the last commit ba9eca1 resulted in a broken build; this is because `MethodChannel.setMockMethodCallHandler` was replaced by `TestDefaultBinaryMessenger.setMockMethodCallHandler` ([ref](https://docs.flutter.dev/release/breaking-changes/mock-platform-channels#description-of-change)). The migration guide indicated that a specific package needed to be imported so the test could behave as expected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/524)

Fix CI issue

---

LICENSE

Fixes #526
This PR de-nests the license copy from a multi-line comment. I believe this is causing issues with tools that attempt to parse a license file to determine the license type. 
MIT license templates:
* https://opensource.org/licenses/MIT
* https://choosealicense.com/licenses/mit/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/527)

Make license file compatible with tools like LicenseBat

---

android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java

Implement the Flutter `ActivityAware` interface to pass the `Activity` context instead of `Application` context to `setAppId`.
Fixes https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/509. What we were experiencing was that on the first run of the app, the current activity would be `null` so that IAMs don't display and the app is sensed as in the background even when in the foreground. Backgrounding the app and returning resumed normal behavior.
Why? After the [changes to support Android V2 embedding](https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/486), the plugin is set up in `onAttachedToEngine` and the Application Context is **not** an instance of Activity.
When this context is eventually passed to `setAppId`, we end up with the current activity is `null` which leads to …

Use `ActivityAware` to get the Activity context

---

android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
android/src/main/java/com/onesignal/flutter/OneSignalSerializer.java
example/lib/main.dart
ios/Classes/OSFlutterCategories.h
ios/Classes/OSFlutterCategories.m
ios/Classes/OneSignalPlugin.h
ios/Classes/OneSignalPlugin.m
ios/onesignal_flutter.podspec
lib/onesignal_flutter.dart
lib/src/in_app_message.dart

Adds the In-App Message Lifecycle Handler which includes up to 4 callbacks for the displaying and dismissing of In-App Messages.
This handler was added to give customers visibility into the display lifecycle of IAMs: when an IAM will be displayed, and also when it has been dismissed.
Extra fields will show up if a user logs the OSInAppMessage instead of just its messageId property, which is fine.
In-App Messages are only read and not modified.
The documentation will need to be updated for react native to provide these new methods.
* Add `onWillDisplayInAppMessage`, `onDidDisplayInAppMessage`, `onWillDismissInAppMessage`, `onDidDismissInAppMessage` handlers to Android and iOS
* Add respective handlers to OneSignal dart file
* Add example handlers to the example app
* Test device using IAM …

Add in app mesage lifecycle handler

---

ios/Classes/OneSignalPlugin.m

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/523)

Add missing fallbackToSettings argument on native iOS side

---

example/lib/main.dart
ios/Classes/OneSignalPlugin.m
lib/onesignal_flutter.dart

Adds the `setLaunchURLsInApp` function that is for iOS only.
The function, previously only available via the native iOS SDK, does the following:
> This method can be used to set if launch URLs should be opened in Safari or within the application. The default value is `true` which opens an in-app browser. Setting this to `false` will open in Safari.
For Android, just log that it is unsupported and don't add to plugin.
* Add `setLaunchURLsInApp` method to OneSignal iOS plugin
* Add `setLaunchURLsInApp` bridge method to onesignal_flutter.dart
* Add `setLaunchURLsInApp` method to the example app with `false`
* **iOS**: Tested on iPhone 13 using the example app calling `setLaunchURLsInApp` with `true` and `false`. Tested with OneSignal-iOS-SDK 3.10.1 that remedied the problem with calling …

Add iOS only `setLaunchURLsInApp` function

---

android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
example/lib/main.dart
ios/Classes/OneSignalPlugin.m
lib/onesignal_flutter.dart

Adds callbacks for setting language (`setLanguage` method).
Provides developers with success and failure callbacks.
* Add `setLanguage` success and failure callbacks to Android and iOS methods.
* On **Android**, if multiple channels are set (ie push, email, SMS), the developer's callback will fire once for the first successful or failed channel and subsequent success or failure callbacks will not be invoked.
* On **iOS**, if multiple channels are set (ie push, email, SMS), the callback will be invoked once with the states of all the channels.
* When testing **Android**, the `onSuccess` response from the native SDK is always `null`. When this is `null`, I pass through a custom object, because passing through the `null` object crashes in Flutter.
```java
{'success' : 'true', 'message' : …
```

[Feature] Add callbacks to `setLanguage`

---

example/lib/main.dart
ios/Classes/OneSignalPlugin.m
ios/onesignal_flutter.podspec
lib/onesignal_flutter.dart

Adds Live Activity support.
Adding 2 SDK methods that allow a customer to register their temporary live activity token with an activity ID on OneSignal's backend:
1. enterLiveActivity
2. exitLiveActivity
Adding bridging to access the two iOS SDK methods.
The iOS repo contains tests, this is only bridging
Testing limited since no real push token is available.
- Tested that the Flutter example app can call these two methods and receive the onFailure response with a correct 404 error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/621)

Add Live Activities support

---

android/build.gradle
ios/onesignal_flutter.podspec
pubspec.yaml

* Bump SDK version to 3.5.0
* iOS has been bumped from 3.11.4 to 3.12.3 already in a prior PR for live activities
* No Android bump to 4.8.3, stay on 4.8.2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/622)

3.5.0 Release

---

example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
example/lib/main.dart
ios/Classes/OSFlutterDebug.h
ios/Classes/OSFlutterDebug.m
ios/Classes/OneSignalPlugin.m
lib/onesignal_flutter.dart
lib/src/onesignaldebug.dart

Create Debug namespace to handle changing visual and text log levels.
User Model requires namespacing to organize functions
Logging methods have been moved to their own namespace and will be invoked as:
`OneSignal.Debug.setLogLevel(OSLogLevel.verbose)`
`OneSignal.Debug.setVisualLevel(OSLogLevel.verbose)`
This PR adds a debug namespace and the relevant iOS bridge, android to follow.
No unit testing was used
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/640)

Adding Debug namespace

---

ios/Classes/OSFlutterDebug.m
ios/Classes/OneSignalPlugin.m
lib/onesignal_flutter.dart
lib/src/debug.dart

Update methods that are under the OneSignal Static Object
Some methods are to remain on the main OneSignal class, with some updates.
Methods to remain on the OneSignal class will be invoked as:
`OneSignal.login("externalId");`
`OneSignal.logout();`
`OneSignal.setPrivacyConsent(true);`
`var consent = OneSignal.getPrivacyConsent();`
`OneSignal.setRequiresPrivacyConsent(true);`
`var requireConsent = OneSignal.getRequiresPrivacyConsent();`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/642)

Adding methods to the OneSignal static object

---

example/ios/Podfile
example/ios/Podfile.lock
example/lib/main.dart
ios/Classes/OSFlutterDebug.m
ios/Classes/OSFlutterNotifications.h
ios/Classes/OSFlutterNotifications.m
ios/Classes/OSFlutterPushSubscription.h
ios/Classes/OSFlutterPushSubscription.m
ios/Classes/OSFlutterUser.m
ios/Classes/OneSignalPlugin.m
ios/onesignal_flutter.podspec
lib/onesignal_flutter.dart
lib/src/debug.dart
lib/src/notification.dart
lib/src/notifications.dart
lib/src/permission.dart
lib/src/pushsubscription.dart
lib/src/subscription.dart
lib/src/user.dart
pubspec.yaml

Notification and pushSubscription namespaces for iOS
`OneSignal.Notifications.setNotificationOpenedHandler((OSNotificationOpenedResult result) { });`
`OneSignal.Notifications.setNotificationOpenedHandler.setNotificationWillShowInForegroundHandler((OSNotificationReceivedEvent event) {});`
`OneSignal.Notifications.addPermissionObserver(OneSignalPermissionObserver);`
`OneSignal.Notifications.removePermissionObserver(OneSignalPermissionObserver);`
`OneSignal.Notifications.clearAll();`
The following two methods are Async and return a bool
`OneSignal.Notifications.registerForProvisionalAuthorization();`
`OneSignal.Notifications.requestPermission(fallbackToSettings);`
`OneSignal.User.pushSubscription.addObserver(OneSignalPushSubscriptionObserver);` …

Notification and pushSubscription namespaces

---

example/lib/main.dart
ios/Classes/OSFlutterLocation.h
ios/Classes/OSFlutterLocation.m
ios/Classes/OneSignalPlugin.m
lib/onesignal_flutter.dart
lib/src/location.dart

Adding the location namespace where a developer can request permission and set whether location is shared or not.
`OneSignal.Location.requestPermission();`
`const shared = OneSignal.Location.isShared()`
`OneSignal.Location.setShared(true);`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/648)

[User Model] Location Namespace

---

example/lib/main.dart
ios/Classes/OSFlutterInAppMessages.h
ios/Classes/OSFlutterInAppMessages.m
ios/Classes/OSFlutterNotifications.h
ios/Classes/OSFlutterNotifications.m
ios/Classes/OneSignalPlugin.m
lib/onesignal_flutter.dart
lib/src/inappmessage.dart
lib/src/inappmessages.dart
lib/src/notifications.dart

Adding the InAppMessages Namespace
```
OneSignal.InAppMessages
.setInAppMessageClickedHandler((OSInAppMessageAction action) {
this.setState(() {
_debugLabelString =
"In App Message Clicked: \n${action.jsonRepresentation().replaceAll("\\n", "\n")}";
});
});
OneSignal.InAppMessages.setOnWillDisplayInAppMessageHandler((message) {
print("ON WILL DISPLAY IN APP MESSAGE ${message.messageId}");
});
OneSignal.InAppMessages.setOnDidDisplayInAppMessageHandler((message) {
print("ON DID DISPLAY IN APP MESSAGE ${message.messageId}");
});
OneSignal.InAppMessages.setOnWillDismissInAppMessageHandler((message) {
print("ON WILL DISMISS IN APP MESSAGE ${message.messageId}");
});
OneSignal.InAppMessages.setOnDidDismissInAppMessageHandler((message) {
print("ON DID DISMISS IN APP MESSAGE …
```

[User Model] InAppMessages Namespace + iOS

---

android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
android/src/main/java/com/onesignal/flutter/OneSignalSession.java

Adding the Android implementation behind the Session namespace
`OneSignal.Session.addOutcome("normal_2");`
`OneSignal.Session.addUniqueOutcome("unique_1");`
`OneSignal.Session.addOutcomeWithValue("value_1", 3.2);`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/653)

[User Model] Session method implementation + Android

---

android/src/main/java/com/onesignal/flutter/OneSignalInAppMessages.java
android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
android/src/main/java/com/onesignal/flutter/OneSignalPushSubscription.java
android/src/main/java/com/onesignal/flutter/OneSignalSerializer.java
android/src/main/java/com/onesignal/flutter/OneSignalUser.java
ios/Classes/OneSignalPlugin.m
lib/onesignal_flutter.dart
lib/src/pushsubscription.dart

OneSignal Namespace
`OneSignal.login("externalId");`
`OneSignal.logout();`
`OneSignal.setPrivacyConsent(true);`
`var consent = OneSignal.getPrivacyConsent();`
`OneSignal.setRequiresPrivacyConsent(true);`
`var requireConsent = OneSignal.getRequiresPrivacyConsent();`
User Namespace
`OneSignal.User.setLanguage("es");`
`OneSignal.User.addAlias("alias_label, alias_value");`
`OneSignal.User.addAliases({alias_label_1: "alias_value_1", alias_label_2: "alias_value_2"});`
`OneSignal.User.removeAlias("alias_label");`
`OneSignal.User.addAliases([alias_label_1, alias_label_2]);`
`OneSignal.User.addEmail("email@email.com");`
`OneSignal.User.removeEmail("email@email.com");`
`OneSignal.User.addSms("+15555555555");`
`OneSignal.User.removeSms("+15555555555");`
`OneSignal.User.addTag("tag_key", …

[User Model] User, pushSubscription and OneSignal namespace method and handler implementation + Android

---

android/src/main/java/com/onesignal/flutter/OneSignalNotifications.java
android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
android/src/main/java/com/onesignal/flutter/OneSignalSerializer.java
ios/Classes/OSFlutterNotifications.m
lib/onesignal_flutter.dart
lib/src/notifications.dart

Notifications namespace method implementation
`OneSignal.Notifications.setNotificationOpenedHandler((OSNotificationOpenedResult result) { });`
`OneSignal.Notifications.setNotificationOpenedHandler.setNotificationWillShowInForegroundHandler((OSNotificationReceivedEvent event) {});`
`OneSignal.Notifications.addPermissionObserver(OneSignalPermissionObserver);`
`OneSignal.Notifications.removePermissionObserver(OneSignalPermissionObserver);`
`OneSignal.Notifications.clearAll();`
The following two methods are Async and return a bool
`OneSignal.Notifications.registerForProvisionalAuthorization();`
`OneSignal.Notifications.requestPermission(fallbackToSettings);`
- - - …

[User Model] Notifications namespace method implementation

---

android/build.gradle
ios/onesignal_flutter.podspec
pubspec.yaml

Bump native iOS SDK version from `3.12.3` to `3.12.4`
- Fix In App Messages occasionally being displayed twice 
- Fix a OneSignal log ignoring the "None" log level
Bump native Android SDK version from `4.8.2` to `4.8.5`
- Fix issue which caused groupless notifications to not get cleared if there were at least 4 of them
- Remove OneSignal gradle plugin from build.gradle files 
- Fix an issue with liquid IAMs when a non-existent tag doesn't show the correct default value.
- Speculative Fix for WorkManager not Initialized Crash
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/670)

Release 3.5.1

---

example/lib/main.dart
lib/onesignal_flutter.dart

Everything on the shared instance of OneSignal should now be called on the static OneSignal namespace.
clean api
tested on iOS and android simulators
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/681)

[User Model ]remove shared from OneSignal and make methods static

---

MIGRATION_GUIDE.md
android/build.gradle
ios/onesignal_flutter.podspec
pubspec.yaml

🚧 Beta release. Please test thoroughly prior to production use. 🚧
[OneSignal Flutter 5.0.0-beta2
](https://pub.dev/packages/onesignal_flutter/versions/5.0.0-beta2)
In this major version beta release for the OneSignal SDK, we are making a significant shift from a device-centered model to a user-centered model. A user-centered model allows for more powerful omni-channel integrations within the OneSignal platform.
For information please see the [migration guide](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/user_model/main/MIGRATION_GUIDE.md).
We have made significant, breaking changes to our functions. Please see the updated migration guide for the most up to date signatures.
* [User model] [Rename Events](https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/678)
* [User Model] …

User Model Beta 2 release

---

ios/Classes/OneSignalPlugin.m

Fixed typo when calling logout method in ios environment description that summaries the changes in this PR.
An error occurs when calling logout with the current version 5.0.0.
Call logout method normally in ios environment
- - - …

fix: typo with logout in ios method invoke channel

---

lib/src/user.dart

Fixes the app crashing when sending non-string tag values.
Fixes #728 
The addTags methods are incorrectly marked as String : Dynamic instead of String : String.
We can either convert from dynamic to string for the developer or release a breaking change to fix the types.
Fix crash
tags
Tested both addTagWithKey and addTag with non-string values
- - - …

Fix crash when sending non-string tag values

---

android/src/main/java/com/onesignal/flutter/OneSignalSerializer.java

Fix crash in Android when receiving a notification with action buttons.
We were converting the ActionButtons to a map so we could not bridge to dart from Android native
Fixes https://github.com/OneSignal/OneSignal-Android-SDK/issues/1815
fix crash
android push notifications
tested with Android push and iOS push
- - - …

Fix crash when using action buttons in Android

---

android/src/main/java/com/onesignal/flutter/OneSignalNotifications.java
ios/Classes/OSFlutterNotifications.m
ios/Classes/OneSignalPlugin.m
ios/onesignal_flutter.podspec
lib/src/notifications.dart

This PR allows the click listener to be fired when the app is closed.
- Bumps the iOS dependency to 5.0.2
- Don't register the bridge click listener until a dart click listener is added.
- Initialize OneSignal native when the plugin is registered
none
Tested on Android and iOS devices with multiple push notifications from a cold start, background, and foreground.
- - -
This …

Fix notification clicked listener firing from cold start

---

android/src/main/java/com/onesignal/flutter/OneSignalNotifications.java
lib/src/notifications.dart

`OneSignal.Notifications.canRequest()` has been fixed for Android in https://github.com/OneSignal/OneSignal-Android-SDK/pull/1798, make it available in Flutter SDK.
Add `OneSignal.Notifications.canRequest()` functionality to Android. It was previously iOS-only, with Android always returning `false`.
Adds `OneSignal.Notifications.canRequest()` functionality to Android. 
Note that the method `OneSignal.Notifications.canRequest()` returns whether or not the device has been prompted for push already, and may not indicate on Android whether or not a push prompt will display.
Testing on Android emulator API 33:
1. New app install and see `canRequest = true`
2. Prompt for push and accept
3. See `canRequest = false` which is correct
- - - …

Add canRequest to Android

---

MIGRATION_GUIDE.md
lib/src/pushsubscription.dart

Update the migrations steps for iOS
Update the comment for optedIn to fix #720 
Also updates migration guide for the iOS import and cocoapods changes #726 
improve documentation
comments and migration guide
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Fl …

Update migration steps for iOS and clarify optIn

---

android/src/main/java/com/onesignal/flutter/OneSignalInAppMessages.java

The Android native bridge will now properly handle clearTriggers.
fixes #767 
`OneSignalInAppMessages.java` was not listening to clearTriggers so an error would throw when calling clearTriggers on 
an Android device.
Fix clearTriggers
IAM triggers
tested on pixel 7
- - - …

Fix clearTriggers on Android

---

.github/workflows/ci.yml
example/lib/main.dart
lib/onesignal_flutter.dart
lib/src/inappmessage.dart
lib/src/notification.dart
lib/src/notifications.dart
lib/src/utils.dart
pubspec.yaml
test/mock_channel.dart
test/onesignalflutter_test.dart

Get the CI to succeed
Make the CI script useful
CI.yml
Formatting of code
pass now
tested running on iOS and Android
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/773)

Fix CI errors

---

android/src/main/java/com/onesignal/flutter/OneSignalUser.java

Resolve all Android user namespace methods over the bridge as some were missed.
Fixes https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/799 
Fixes https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/789
Resolve all User namespace methods over the Android bridge, some of them were missed like `addTag` or `removeTag`. This was only for people using `await` with these methods and waiting on the response, doesn't change any implementation details.
None
Android Nexus S Emulator API 33, tested with calling `addTag` with `await` and seeing that it resolves after these changes.
```
await OneSignal.User.addTagWithKey("test2", "val2");
```
- - - …

Fix Android User calls to always resolve

---

ios/Classes/OSFlutterUser.m
lib/src/user.dart

Fixes removeEmail calls on Android and iOS and removeSms calls on iOS
Fixes errors when calling removeEmail on Android and iOS and removeSms on iOS
No changes to the public API as fixes apply to native calls to OneSignal Android and iOS SDKs
Call arguments for removeEmail and removeSms do not have defined keys in user.dart and calling with a key returns an error on iOS.
Fix could be done one of 2 ways:
1. Remove the key value in OSFlutterUser.m
- What was done in this PR
2. Add the key value defined in OSFlutterUser.m (@"email", @"smsNumber") to user.dart
- This also requires the key value to be added to Android in OneSignalUser.java
Tested removeEmail and removeSms on an user with emails and sms subscriptions and with none, app build of the OneSignal example app on on a emulated Pixel 4 …

[Fix] Remove email and remove sms

---

android/src/main/java/com/onesignal/flutter/OneSignalNotifications.java

Resolve `requestPermission` call if permission is already granted.
**Problem:**
If permission is already enabled, the native call to `OneSignal.getNotifications().requestPermission(fallbackToSettings, Continue.with(...)` never suspends and the Continuation code block never runs. As a result, we would not be able to resolve the promise over the bridge.
**Solution:**
Before calling that method, do a permission check and return **true**. 
I chose to check the permission in Android bridge instead of resolving early in Dart because the Dart-level `_permission` boolean may not be set yet when `requestPermission` is called soon after initialization. I ran into this case when testing the following scenario:
Test scenario
```dart
// Notification permission has already been granted …
```

[fix] Android: Resolve `requestPermission` call when already granted

---

android/build.gradle

This PR provide the package namespace if the AGP is equal or higher then 8. 
This PR is a cherry-pick of this main branch PR https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/765 for the user_model branch.
By adding the namespace condition for AGP 8 and higher, this fix the issue [Bug]: AGP 8 not supported #764 
Tested during the Gradle sync with AGP 9
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/825)

[user model] Added the namespace property in build.gradle

---

android/build.gradle
android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
ios/Classes/OneSignalPlugin.m
ios/onesignal_flutter.podspec
pubspec.yaml

**🎉 New Methods**
* Add public `getTags` method #804 
**🔧 Maintenance**
* Added the namespace property in build.gradle for AGP 8 #825
🐛 **Bug Fixes**
* Fix Android User calls to always resolve #800
* [Fix] Remove email and remove sms #805
* [fix] Android: Resolve `requestPermission` call when already granted #806
**⚠️ Behavior Changes ⚠️**
* Location sharing with OneSignal now defaults to **false**: You will need to explicitly enable location sharing with OneSignal with `OneSignal.Location.setShared(true)`
- Update iOS SDK from `5.0.4` to `5.1.0`: [Release notes](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.1.0)
- Update Android SDK from `5.0.4` to `5.1.2`: [Release notes](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.2)
- - - …

Release 5.1.0

---

MIGRATION_GUIDE.md
android/src/main/java/com/onesignal/flutter/OneSignalSerializer.java
android/src/main/java/com/onesignal/flutter/OneSignalUser.java
example/lib/main.dart
ios/Classes/OSFlutterUser.m
lib/onesignal_flutter.dart
lib/src/user.dart

Add getters for onesignal ID and external ID, and a user state observer to know when these values are changed.
From developer feedback and to support integration partners, we are exposing the onesignal ID and external ID with getters.
We also want to grant developers the ability to add observers that can be called when there is a change in user state.
Manually tested on:
- Pixel 7 Pro Emulator running Android 14
- iPhone 15 Pro running iOS 17.2
Tested adding observer for user state and calling new methods to access externalId and onesignalId. Ensured congruency between iOS and Android responses.
- Simplify with less code, followed by splitting up code into well named …

Add user state observer and ID getters

---

ios/Classes/OneSignalPlugin.m

Fix the Live Activities `enter` and `exit` methods were not working by registering the Live Activities class with Flutter.
Fix error
```
Unhandled Exception: MissingPluginException(No implementation found for method 
OneSignal#enterLiveActivity on channel OneSignal#liveactivities)
```
Bug fix that didn't register the `OSFlutterLiveActivities` class.
- Physical iphone 13 with ios 17.2
- Call `OneSignal.LiveActivities.enterLiveActivity("activityId", "token")` and `OneSignal.LiveActivities.exitLiveActivity("activityId")`
- Before PR: encounter that error
- After PR: See the native enter and exit requests get logged and receive successful network response
- - - …

Fix Live Activities methods were not working due to bridge error

---

android/build.gradle
android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
ios/Classes/OneSignalPlugin.m
ios/onesignal_flutter.podspec
pubspec.yaml

What's New
--------
Starting with iOS 17.2, Live Activities can now be started via push notification ([Apple's documentation](https://developer.apple.com/documentation/activitykit/starting-and-updating-live-activities-with-activitykit-push-notifications#Start-new-Live-Activities-with-ActivityKit-push-notifications)). This change enhances the OneSignal SDK to provide application's access to the full suite of Live Activity functionality.
To use Push To Start Live Activities, see documentation on [How to start a Live Activity with a remote push notification](https://documentation.onesignal.com/docs/push-to-start-live-activities).
**Default Live Activity**
The concept of a "Default" Live Activity has been established in the SDK, which eliminates the need for a customer app to define and …

Release 5.2.0

---

android/build.gradle
android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
ios/Classes/OneSignalPlugin.m
ios/onesignal_flutter.podspec
pubspec.yaml

🔧 Native SDK Dependency Updates
--------
For full changes, [see the native release notes](https://github.com/OneSignal/OneSignal-Android-SDK/releases)
- Xiaomi notification click was not foregrounding app https://github.com/OneSignal/OneSignal-Android-SDK/pull/2129
- FCM push token was not being refreshed (https://github.com/OneSignal/OneSignal-Android-SDK/pull/2125, https://github.com/OneSignal/OneSignal-Android-SDK/pull/2118)
- Poll for notification permission changes to detect permission change when prompting outside of OneSignal https://github.com/OneSignal/OneSignal-Android-SDK/pull/2112
- WorkManager fixes when the app uses a custom WorkManager https://github.com/OneSignal/OneSignal-Android-SDK/pull/2122
- Cold start creates new session and refreshes the user from the server …

Release 5.2.1

---

lib/onesignal_flutter.dart

This method is misleading. it is not implemented but the package exposes it. Please remove it or annotate it.
Errors from Android in device logs:
```
06-12 23:50:13.470 21589 21742 D OneSignal: [DefaultDispatcher-worker-2] HttpClient: Got Response = POST https://api.onesignal.com/apps/<REDUCTED-UUID>/users - FAILED STATUS: 400
06-12 23:50:13.478 21589 21742 W OneSignal: [DefaultDispatcher-worker-2] HttpClient: Got Response = POST - STATUS: 400 - Body: {"errors":[{"title":"uuid: incorrect UUID length 42 in string \"local-<REDUCTED-UUID>\""}]}
```
Error from iOS in API request:
curl:
```
curl 'https://api.onesignal.com/apps/<REDUCTED-UUID>/users' \
-X POST \
-H 'Host: api.onesignal.com' \
-H 'Connection: keep-alive' \
-H 'Accept: application/vnd.onesignal.v1+json' \
-H 'SDK-Version: …
```

chore: add warning for identity verification

---

ios/Classes/OneSignalPlugin.m

On the native iOS SDK, set the wrapper SDK type first before calling initialize.
* Set the wrapper SDK type first so when initialize is called, the native SDK can check if the SDK is a wrapper type in order to conditionally omit a misleading fatal log
* See https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1468
* Safe to re-order, as other wrapper SDKs already do
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/932)

Set wrapper sdk type before calling initialize

---

android/build.gradle
example/android/app/build.gradle

Fix lStar not  found error due to `compileSdkVersion` being to old.
SDK should compatible with Fluter 3.24.0 and newer.
Only effect Android compile settings
Fixes issue #930
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/935)

set compileSdkVersion 34 to fix build errors

---

android/build.gradle
ios/onesignal_flutter.podspec
pubspec.yaml

--------
**⚠️ Please update to this release to ensure launch URLs continue to work on iOS 18 devices ⚠️**
**🐛 Bug Fixes**
- https://github.com/OneSignal/OneSignal-Android-SDK/pull/2123
- https://github.com/OneSignal/OneSignal-Android-SDK/pull/2062
- https://github.com/OneSignal/OneSignal-Android-SDK/pull/2063
**🔧 Maintenance**
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1493
**✨ Improvements**
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1494
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/962)

Release 3.5.4

---

android/build.gradle
android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
ios/Classes/OneSignalPlugin.m
ios/onesignal_flutter.podspec
pubspec.yaml

--------
🐛 Bug Fixes
* Fix setting consentGiven throwing if called before initWithContext [#2200](https://github.com/OneSignal/OneSignal-Android-SDK/pull/2200)
* Window manager BadTokenException / WindowLeaked [#2208](https://github.com/OneSignal/OneSignal-Android-SDK/pull/2208)
✨ Improvements
* Make use of ryw_delay to minimize retries on IAM fetch [#2207](https://github.com/OneSignal/OneSignal-Android-SDK/pull/2207)
✨ Improvements
- Don't use cached in-app messages if the SDK encounters an error fetching them or when the server returns none [#1499](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1499)
- Improve segment membership calculation that allows for fetching more accurate and updated in-app messages for a user …

Release 5.2.7

---

android/build.gradle
android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
ios/Classes/OneSignalPlugin.m
ios/onesignal_flutter.podspec
pubspec.yaml

--------
🐛 Bug Fixes
- [Fix] NPE by getScheduleBackgroundRunIn [OneSignal/OneSignal-Android-SDK#2212](https://github.com/OneSignal/OneSignal-Android-SDK/pull/2212)
🐛 Bug Fixes
- Fix [__NSPlaceholderDictionary initWithObjects:forKeys:count:] crashes caused by nil HTTPResponse headers [OneSignal/OneSignal-iOS-SDK#1518](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1518)
✨ Improvements
- Include debug symbols (dSYM) in the SDK [OneSignal/OneSignal-iOS-SDK#1519](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1519)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-Flutter-SDK/976)

Release 5.2.8

---

android/src/main/java/com/onesignal/flutter/FlutterMessengerResponder.java
android/src/main/java/com/onesignal/flutter/FlutterRegistrarResponder.java
android/src/main/java/com/onesignal/flutter/OneSignalDebug.java
android/src/main/java/com/onesignal/flutter/OneSignalInAppMessages.java
android/src/main/java/com/onesignal/flutter/OneSignalLocation.java
android/src/main/java/com/onesignal/flutter/OneSignalNotifications.java
android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
android/src/main/java/com/onesignal/flutter/OneSignalPushSubscription.java
android/src/main/java/com/onesignal/flutter/OneSignalSerializer.java
android/src/main/java/com/onesignal/flutter/OneSignalSession.java
android/src/main/java/com/onesignal/flutter/OneSignalUser.java

Drop support for Android v1 embedding, which is quite old.
The main changes are in one commit: [60dcfc](https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/1005/commits/60dcfc407537270c1992584cccd252d287557e7a) while others are nits.
* Remove references to the now deprecated v1 Android embedding. 
* The SDK used classes `PluginRegistry.Registrar` and `io.flutter.view.FlutterNativeView` 
* However, to support newer Flutter versions, we now need to completely drop v1 support.
* Investigated other PRs in open-source repositories
Reported in https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/928
Users targeting Flutter master and beta/stable releases after (but not including) `3.27` will fail to compile if the plugin has references any v1 embedding classes.
- Drop support for …

[breaking] Remove deprecated Android v1 embedding references

---

android/src/main/java/com/onesignal/flutter/OneSignalNotifications.java

Don't crash on Android < 7.0 when request permission is called, by using the lower-level API directly instead of a helper.
* The OneSignal-defined `Continue.with` [helper](https://github.com/OneSignal/OneSignal-Android-SDK/blob/1cb29538beaa12b8a19c9bc55d950800fea9f7f7/OneSignalSDK/onesignal/core/src/main/java/com/onesignal/Continue.kt#L59-L65) is only available on API 24 (Android 7.0).
* We still aim to support Android 5 and 6, so don't use this wrapper helper and use the `Continuation` class directly.
https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/981
None
Not tested on old Android versions.
Tested on emulator with API 33:
1. Request permission and deny. Function suspends and returns `false` to the caller.
2. Request permission and accept. Function suspends and returns `true` …

Don't crash with Android < 7.0 (when requesting permission)

---

android/build.gradle
android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java
ios/Classes/OneSignalPlugin.m
ios/onesignal_flutter.podspec
pubspec.yaml

- #1005 
- #1007 
- when upgrading from v3 to v5 of this SDK, notifications will be received when the app has not been opened yet [Android fix](https://github.com/OneSignal/OneSignal-Android-SDK/pull/2244)
---------
**Update Android SDK from 5.1.26 to 5.1.29 | select fixes listed**
- [add Amazon IAP v3.0.5 handle](https://github.com/OneSignal/OneSignal-Android-SDK/pull/2255)
- [fix issue with notification click not foregrounding the app on the first click in certain scenarios](https://github.com/OneSignal/OneSignal-Android-SDK/pull/2259)
- [fix rare 400 issues that happen on new installs](https://github.com/OneSignal/OneSignal-Android-SDK/pull/2059)
- See [release notes](https://github.com/OneSignal/OneSignal-Android-SDK/releases) for full details.
**Update iOS SDK from 5.2.9 to 5.2.10 | …

Release 5.3.0

---

lib/src/location.dart

**REQUIRED** - The descriptions for the two methods setShared and isShared (under the Location module) appear to have been switched. This change switches them back to how they probably should be.
**REQUIRED -** Having docs that are correct is nice!
- x ] I have reviewed this PR myself, ensuring it meets each checklist item
- - - …

Switch docs for setShared and isShared
